/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:e580aeda-abc7-45d6-b6da-aeeca773e4e4",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_qivhF7qhJ",
    "aws_user_pools_web_client_id": "107jv1nsd560rflpqq7g1qpp0v",
    "oauth": {},
    "aws_cloud_logic_custom": [
        {
            "name": "contactEmailer",
            "endpoint": "https://qy5g99rqqc.execute-api.us-east-1.amazonaws.com/staging",
            "region": "us-east-1"
        }
    ],
    "aws_user_files_s3_bucket": "ddrlivecontent172220-staging",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
